power_size:
  loanAmnt: 0.5
  interestRate: 0.4
  installment: 0.5
  employmentTitle: 0.2
  annualIncome: 0.15
  postCode: 0.5
  dti: 0.16
  revolBal: 0.15
  revolUtil: 0.2
  openAcc: 0.4
  totalAcc: 0.2
  n1: 0.3
  n2: 0.3
  n3: 0.3
  n4: 0.3
  n5: 0.3
  n6: 0.3
  n7: 0.3
  n8: 0.3
  n9: 0.3
  n10: 0.3
  n14: 0.3



