SVM:
  C: 0.1
  coef0: 0.5
  degree: 10
  gamma: 0.1
  kernel: linear
XGBoost:
  gamma: 0.1
  learning_rate: 0.01
  max_depth: 40
  n_estimators: 300
decision_tree:
  criterion: gini
  max_depth: 15
  max_features: null
  min_samples_leaf: 600
  min_samples_split: 100
random_forest:
  max_depth: 15
  min_samples_split: 200
  n_estimators: 100
MLP: 
  hidden_size1: 256
  hidden_size2: 64
  hidden_size3: 16
  output_size: 1
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 20